language: java
script: cd com.rainerschuster.webidl.releng/ && mvn clean install -Pepp.package.webidl && cd ..
deploy:
  provider: releases
  api_key:
    secure: JRYSLpQkaTcASVEG1kiq29tzVuDriLpT3PorHdXLJ067z5AeJqt8laIgKd22epns9P9qE+DzppxLIE9wztRABkfyIRGjH6zn+Ow8YBtl46Qi8wuVQC/afy279a5WQnbPGO/QgOkDmB04vTOlw5CGPRlEx39Vn6THfp+dbwnrWzk=
  file:
    - "./com.rainerschuster.epp.package.webidl.product/target/products/eclipse-webidl-linux.gtk.x86.tar.gz"
    - "./com.rainerschuster.epp.package.webidl.product/target/products/eclipse-webidl-linux.gtk.x86_64.tar.gz"
    - "./com.rainerschuster.epp.package.webidl.product/target/products/eclipse-webidl-macosx.cocoa.x86_64.tar.gz"
    - "./com.rainerschuster.epp.package.webidl.product/target/products/eclipse-webidl-win32.win32.x86.zip"
    - "./com.rainerschuster.epp.package.webidl.product/target/products/eclipse-webidl-win32.win32.x86_64.zip"
  skip_cleanup: true
  on:
    repo: rainerschuster/webidl-eclipse
    tags: true
    all_branches: true
