/*
 * generated by Xtext
 */
package com.rainerschuster.webidl.ui.contentassist

import com.rainerschuster.webidl.ui.contentassist.AbstractWebIDLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class WebIDLProposalProvider extends AbstractWebIDLProposalProvider {
}
