/*
* generated by Xtext
*/
package com.rainerschuster.webidl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WebIDLStandaloneSetup extends WebIDLStandaloneSetupGenerated{

	public static void doSetup() {
		new WebIDLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

