/*
 * generated by Xtext
 */
package com.rainerschuster.webidl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WebIDLRuntimeModule extends com.rainerschuster.webidl.AbstractWebIDLRuntimeModule {

}
