/*
 * generated by Xtext
 */
package com.rainerschuster.webidl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WebIDLUiModule extends com.rainerschuster.webidl.ui.AbstractWebIDLUiModule {
	public WebIDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
